// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function blake2b(length) {
  return /* BLAKE2B */Block.__(0, [length]);
}

function blake2s(length) {
  return /* BLAKE2S */Block.__(1, [length]);
}

var md5 = /* MD5 */0;

var sha1 = /* SHA1 */1;

var rmd160 = /* RMD160 */2;

var sha224 = /* SHA224 */3;

var sha256 = /* SHA256 */4;

var sha384 = /* SHA384 */5;

var sha512 = /* SHA512 */6;

var whirlpool = /* WHIRLPOOL */7;

exports.md5 = md5;
exports.sha1 = sha1;
exports.rmd160 = rmd160;
exports.sha224 = sha224;
exports.sha256 = sha256;
exports.sha384 = sha384;
exports.sha512 = sha512;
exports.whirlpool = whirlpool;
exports.blake2b = blake2b;
exports.blake2s = blake2s;
/* No side effect */
